services:
  - type: web
    name: order-backend
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Order-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
